export const goods = [
  {
    id: "0",
    new: true,
    favorite: false,
    pic: "1.jpg",
    description: "Foxxx Kitsune Mini Black Vintage RCA",
    price: "75",
    available: true,
  },
  {
    id: "1",
    new: true,
    favorite: false,
    pic: "2.jpg",
    description: "Foxxx Viper Fox Golden Vintage Lot #1 RCA",
    price: "100",
    available: true,
  },
  {
    id: "2",
    new: false,
    favorite: false,
    pic: "3.jpg",
    description: "Нитровиниловые перчатки Wally Plastic S",
    price: "5",
    available: true,
  },
  {
    id: "3",
    new: true,
    favorite: false,
    pic: "4.jpg",
    description: "Forever Cartridge Grip Ergo 30 mm Огненно-Рыжий",
    price: "25",
    available: false,
  },
  {
    id: "4",
    new: false,
    favorite: false,
    pic: "5.jpg",
    description: "Verge Direct 2.1 Pink gip EGO 4 mm liners",
    price: "25",
    available: false,
  },
  {
    id: "5",
    new: true,
    favorite: false,
    pic: "6.jpg",
    description: "Deuce Machines Direct Drive #7 RCA Samurai",
    price: "95",
    available: true,
  },
  {
    id: "6",
    new: false,
    favorite: false,
    pic: "7.jpg",
    description: "Cyborg Machines Alter Rotary Axis Cross Sexy Nymph",
    price: "120",
    available: true,
  },
  {
    id: "7",
    new: false,
    favorite: false,
    pic: "8.jpg",
    description: "Verge Direct 2.1 Gunmetal",
    price: "140",
    available: false,
  },
];
